### PR TITLE
Add workflow for deploying a demo to GitHub Pages

### LINKED ISSUE #4: Demo using binder
Create a binder config to run on mybinder, allowing people to try it out easily.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #4

### CODE REVIEW

**Comment by jtpio** [comment]
Looking good trying the built archive locally:

image

**Comment by jtpio** [comment]
Merging to see if that works on the real GitHub pages deployment.

**Comment by ianthomas23** [comment]
Thanks for this!

**Comment by ianthomas23** [comment]
To clarify, if we make changes to `cockle` then for them to appear in the github pages deployment we need a new release of `cockle` and a PR or push to `main` branch here?

**Comment by jtpio** [comment]
Yes we need to update the dependency in `package.json` (and update the `yarn.lock`):

https://github.com/jupyterlite/terminal/blob/2f20f35e82aae60c5d191660d06cf3be70500332/package.json#L63

And open a PR here and merge it into `main`.

**Pull request merged**
